print(" Data Diri Mahasiswa ".center(40,"="))
name = input("Masukan Nama Anda ? ").capitalize()
nim = input("Masukan NIM Anda ? ")
prody = input("Masukan Prody Anda ? ").capitalize()
address = input("Masukan Alamat Anda ? ").capitalize()

print("\nHasil cetak data diatas adalah")
print("Nama     : " + name)
print("Nim      : " + nim)
print("Prody    : " + prody)
print("Alamat   : " + address)
